# Generated by Django 4.2.3 on 2023-08-06 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50, unique=True, verbose_name='alias')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('race', models.CharField(choices=[('Hu', 'humano'), ('Mu', 'mutante')], default=('M', 'male'), max_length=8, verbose_name='raza')),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=8, verbose_name='genero')),
                ('age', models.IntegerField(verbose_name='edad')),
                ('born', models.DateField(null=True, verbose_name='nacimiento')),
                ('length', models.IntegerField(null=True, verbose_name='estatura')),
                ('weight', models.IntegerField(null=True, verbose_name='estatura')),
                ('popularity', models.IntegerField(default=1, verbose_name='popularidad')),
                ('is_died', models.BooleanField(default=True, verbose_name='vivo')),
                ('avatar', models.ImageField(null=True, upload_to='characters/', verbose_name='avatar')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='creacion')),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characters',
            },
        ),
    ]
