# Generated by Django 4.2.3 on 2023-08-06 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='age',
        ),
        migrations.RemoveField(
            model_name='character',
            name='born',
        ),
        migrations.AlterField(
            model_name='character',
            name='created_at',
            field=models.DateField(verbose_name='creacion'),
        ),
        migrations.AlterField(
            model_name='character',
            name='length',
            field=models.FloatField(null=True, verbose_name='estatura'),
        ),
        migrations.AlterField(
            model_name='character',
            name='weight',
            field=models.FloatField(null=True, verbose_name='peso'),
        ),
    ]
