# Generated by Django 4.2.3 on 2023-08-06 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_remove_character_age_remove_character_born_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nombre')),
                ('description', models.CharField(max_length=200, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Abilities',
                'verbose_name_plural': 'Abilities',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='nombre')),
                ('description', models.CharField(max_length=200, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Profession',
                'verbose_name_plural': 'Professions',
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('description', models.CharField(max_length=100, null=True, verbose_name='description')),
                ('image', models.ImageField(upload_to='weapons/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Weapon',
                'verbose_name_plural': 'Weapons',
            },
        ),
        migrations.RemoveField(
            model_name='character',
            name='created_at',
        ),
        migrations.AddField(
            model_name='character',
            name='bio',
            field=models.TextField(null=True, verbose_name='biografia'),
        ),
        migrations.AddField(
            model_name='character',
            name='created_at_year',
            field=models.IntegerField(null=True, verbose_name='año de creacion'),
        ),
        migrations.AddField(
            model_name='character',
            name='logo',
            field=models.ImageField(default=1, upload_to='logos/', verbose_name='logo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='character',
            name='abilities',
            field=models.ManyToManyField(to='characters.abilities', verbose_name='abilities'),
        ),
        migrations.AddField(
            model_name='character',
            name='occupation',
            field=models.ManyToManyField(to='characters.profession', verbose_name='occupations'),
        ),
        migrations.AddField(
            model_name='character',
            name='weapons',
            field=models.ManyToManyField(to='characters.weapon', verbose_name='weapons'),
        ),
    ]
