# Generated by Django 4.2.3 on 2023-08-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='/static/media/thumbnails/no-img.jpg', upload_to='thumbnails/', verbose_name='imagen')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='creacion')),
                ('updated_at', models.DateField(auto_now_add=True, verbose_name='actualizacion')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
