# Generated by Django 4.2.3 on 2023-08-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
        ('comic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='characters',
            field=models.ManyToManyField(to='characters.character', verbose_name='characters'),
        ),
    ]
